from __future__ import annotations

from CORTEX.thalamus.models import DiagnosisRequest, DiagnosisResult, SourceTrace


class DiagnosisAdapter:
    """Typed boundary for the specialized clinical Diagnosis Engine.

    Diagnosis remains a separate clinical subsystem. This adapter deliberately
    reports the integration as missing until the real engine interface is wired;
    it does not fabricate findings or imply that a clinical evaluation occurred.
    """

    def evaluate(self, request: DiagnosisRequest) -> DiagnosisResult:
        return DiagnosisResult(
            findings={},
            source=SourceTrace(
                kind="diagnosis",
                id="runtime.diagnosis_adapter",
                status="missing",
                detail=(
                    "Diagnosis Engine exists separately; adapter connection is pending. "
                    "No clinical findings were generated by this adapter."
                ),
            ),
        )
